plugin: aws_ec2
regions:
   - us-east-1
hostnames:
  - instance-id
groups:
  webtier: "'sneha-webtier_lt' in (tags.Name)"
  applicationtier: "'sneha-apptier_lt' in (tags.Name)"

filters:
  instance-state-name: running