# ---
# - name: configure backend servers
#   hosts: applicationtier
#   gather_facts: true
#   become: true
#   roles:
#     - backend
#   vars:
#     ansible_connection: aws_ssm
#     ansible_aws_ssm_bucket_name: 8586-terraform-state 
#     ansible_aws_ssm_timeout: 300

- name: configure frontend servers
  hosts: webtier
  gather_facts: true
  become: true
  roles:
    - frontend
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: 8586-terraform-state 
    ansible_aws_ssm_timeout: 300 

